a1 = input('Digite algo: ')
print(type(a1))
print('É um número?', a1.isnumeric())
print('É uma letra?', a1.isalpha())
print('É uma letra e/ou um número?', a1.isalnum())
print('É um espaço?', a1.isspace())
print('É decimal?', a1.isdecimal())
print('Está escrito somente em letras maiúsculas?', a1.isupper())
print('Está escrito somente em letras minúsculas?', a1.islower())
